server:
  port: 9000
  compression:
    enabled: true
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Development?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-mail-here
    password: password-here
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

app:
  jwt:
    secret: JwtGiftBookSecret
    expiration: 150000000